const allElectronicsTags = [
    'smartphone',
    'laptop',
    'headphone',
    'smart watch',
    'camera',
    'gaming console',
    'speaker',
    'wearable',
    'drone',
    'accessory',
    'tablet',
    'desktop computer',
    'printer',
    'monitor',
    'external hard drive',
    'keyboard',
    'mouse',
    'vr headset',
    'networking equipment',
    'home automation',
    'projector',
    'software',
    'microphone',
    'webcam',
    'gps',
    'calculator',
    'flash drive',
    'bluetooth speaker',
    'bluetooth headset',
    'bluetooth keyboard',
    'bluetooth mouse',
    'bluetooth adapter',
    'bluetooth dongle',
    'bluetooth headphones',
    'bluetooth earbuds',
    'bluetooth earphones',
    'bluetooth earpiece',
    'bluetooth earset',
    'iphone',
    'ipad',
    'ipod',
    'macbook',
    'imac',
    'apple watch',
    'apple tv',
    'apple pencil',
    'apple airpods',
    'apple homepod',
    'apple homepod mini',

  ];
  
  export default allElectronicsTags;
  