const allHousingTags = [
    'apartment',
    'house',
    'condo',
    'studio',
    'loft',
    'cottage',
    'villa',
    'townhouse',
    'duplex',
    'penthouse',
    'bedroom',
    'living room',
    'kitchen',
    'bathroom',
    'office',
    'patio',
    'balcony',
    'garden',
    'pool',
    'garage',
    'furnished',
    'unfurnished',
    'modern',
    'vintage',
    'rustic',
    'minimalist',
    'cozy',
    'luxury',
    'renovated',
    'pet-friendly',
    'sofa',
    'bed',
    'table',
    'chair',
    'desk',
    'wardrobe',
    'bookshelf',
    'dining table',
    'coffee table',
    'nightstand',
    'lamp',
    'rug',
    'couch',
    'dresser',
    'mirror',
    'shelves',
    'ottoman',
    'barstool',
    'hanging chair',
  ];
  
  export default allHousingTags;
  